[app]
    app_env = 'dev'
    git_commit_hash = ''
    hostname = ''
    port = ''
    service_name = 'beta-users-ai-tester'

[logger]
    level = 'debug'

[sys_config]
    base_chromadb_dir = "processed_documents/chroma_db"
    default_n_results = 5

[model]
    model_name = "gemini-2.5-pro-exp-03-25"
    # azure_model_name = "Azure-gpt-model"
    # gemini_model_name = "gemini-2.5-pro-exp-03-25"
    embedding_model = "all-MiniLM-L6-v2"

[service]
# placeholder for config for future api service